image: python:latest

before_script:
  - python3 -m venv venv
  - source venv/bin/activate
  - CURRENT_VERSION=$(git describe --tags --abbrev=0)
  - sed -i "s/SEMANTIC_VERSION/$CURRENT_VERSION/" ${CI_PROJECT_DIR}/pyproject.toml
  - sed -i "s/SEMANTIC_VERSION/$CURRENT_VERSION/" ${CI_PROJECT_DIR}/raster2stac/_version.py
  - python3 -m pip install --upgrade pip
  - pip install .

stages:
  - package_test
  - package_build
  - package_deployment

test_package:
  stage: package_test
  script:
    - python3 -m pip install --upgrade pytest
    - pytest tests/*

build_package:
  stage: package_build
  script:
    - python3 -m pip install --upgrade setuptools>=61.0
    - python3 -m pip install --upgrade build
    - python3 -m build
  artifacts:
    paths:
      - dist/*

staging_testpypi:
  stage: package_deployment
  variables:
    TWINE_USERNAME: $STAGING_USERNAME
    TWINE_PASSWORD: $STAGING_TOKEN
  script:
    - python3 -m pip install --upgrade twine
    - twine upload --repository testpypi dist/*
  only:
    - tags

production_pypi:
  stage: package_deployment
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_TOKEN
  script:
    - python3 -m pip install --upgrade twine
    - twine upload dist/*
  only:
    - release
