image: python:latest

before_script:
  - conda env create -f environment.yaml

stages:
  - package_test
  - package_build
  - package_deployment

test_package:
  stage: package_test
  script:
    - pytest tests/

build_package:
  stage: package_build
  script:
    - CURRENT_VERSION=$(git describe --tags --abbrev=0)
    - sed -i "s/SEMANTIC_VERSION/$CURRENT_VERSION/" ${CI_PROJECT_DIR}/pyproject.toml
    - sed -i "s/SEMANTIC_VERSION/$CURRENT_VERSION/" ${CI_PROJECT_DIR}/raster2stac/_version.py
    - python3 -m build
  artifacts:
    paths:
      - dist/*

staging_testpypi:
  stage: package_deployment
  variables:
    TWINE_USERNAME: $STAGING_USERNAME
    TWINE_PASSWORD: $STAGING_TOKEN
  script:
    - twine upload --repository testpypi dist/*
  only:
    - tags

production_pypi:
  stage: package_deployment
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_TOKEN
  script:
    - twine upload dist/*
  only:
    - release
