image: continuumio/miniconda3

stages:
  - environment_setup
  - package_test
  - package_build
  - package_deployment

setup:
  stage: environment_setup
  script: 
    - conda init bash
    - source ~/.bashrc
    - conda env create -f environment.yaml
    - conda activate raster2stac
  artifacts:
    paths:
      - ~/.conda

test_package:
  stage: package_test
  script:
    - conda activate raster2stac
    - pytest tests/

build_package:
  stage: package_build
  script:
    - CURRENT_VERSION=$(git describe --tags --abbrev=0)
    - sed -i "s/SEMANTIC_VERSION/$CURRENT_VERSION/" ${CI_PROJECT_DIR}/pyproject.toml
    - sed -i "s/SEMANTIC_VERSION/$CURRENT_VERSION/" ${CI_PROJECT_DIR}/raster2stac/_version.py
    - conda activate raster2stac
    - python3 -m build
  artifacts:
    paths:
      - dist/*

staging_testpypi:
  stage: package_deployment
  variables:
    TWINE_USERNAME: $STAGING_USERNAME
    TWINE_PASSWORD: $STAGING_TOKEN
  script:
    - twine upload --repository testpypi dist/*
  only:
    - tags

production_pypi:
  stage: package_deployment
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_TOKEN
  script:
    - twine upload dist/*
  only:
    - release
