name: raster2stac
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=2.2.2
  - geopandas=0.14.4
  - dask-geopandas=0.3.1
  - xarray=2024.5.0
  - rioxarray=0.15.5
  - rasterio=1.3.10
  - botocore=1.34.124
  - dask=2024.5.2
  - dask-geopandas=0.3.1
  - pystac=1.10.1
  - ujson=5.10.0
  - fsspec=2024.6.0
  - pytest=8.2.2
  - pip=24.0
  - pip:
    - boto3
    - rio-cogeo
    - openeo-processes-dask[implementations]
    - openeo-pg-parser-networkx<=2024.4.0
    - pystac-client
    - openeo
    - rio-stac
    - build
    - setuptools>=61.0
    - twine
    - stac_validator
